/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_axhl_util_NativeLib */

#ifndef _Included_cn_axhl_util_NativeLib
#define _Included_cn_axhl_util_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_axhl_util_NativeLib
 * Method:    GetNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_axhl_util_NativeLib_GetNativeString
  (JNIEnv *, jclass);

/*
 * Class:     cn_axhl_util_NativeLib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_axhl_util_NativeLib_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
